var car = "supra";
var car1 = "swift";
var car2 = "sonata";
var car3 = "skyline";
var car4 = "suzuki";
console.log("Is car == 'supra'? I predict true");
console.log(car == "supra");
console.log("Is car == 'toyota'? I predict false");
console.log(car == "toyota");
console.log("Is car == 'swift'? I predict true");
console.log(car1 == "swift");
console.log("Is car == 'toyota'? I predict false");
console.log(car1 == "toyota");
console.log("Is car == 'sonata'? I predict true");
console.log(car2 == "sonata");
console.log("Is car == 'toyota'? I predict false");
console.log(car2 == "toyota");
console.log("Is car == 'skyline'? I predict true");
console.log(car3 == "skyline");
console.log("Is car == 'toyota'? I predict false");
console.log(car3 == "toyota");
console.log("Is car == 'suzuki'? I predict true");
console.log(car4 == "suzuki");
console.log("Is car == 'toyota'? I predict false");
console.log(car4 == "toyota");
// Create at least 10 tests. Have at least 5 tests evaluate to True and another 5 tests evaluate to False.
